export const tools = [
  {
    id: 1,
    title: "Merge PDF",
    description: "Combine multiple PDF files into a single document",
    icon: "src/assets/merge.svg",
    link: "/merge-pdf",
    new: true,
  },
  {
    id: 2,
    title: "Split PDF",
    description: "Divide a single PDF into multiple separate files",
    icon: "src/assets/split.svg",
    link: "/split-pdf",
    new: true,
  },
  {
    id: 3,
    title: "Compress PDF",
    description: "Reduce the file size of your PDF documents.",
    icon: "src/assets/compress.svg",
    link: "/compress-pdf",
    new: true,
  },
  {
    id: 4,
    title: "PDF to Word",
    description: "Transform PDF file into editable word document",
    icon: "src/assets/pdftoword.svg",
    link: "/pdf-to-word",
    new: true,
  },
  {
    id: 5,
    title: "PDF to Excel",
    description: "Transform PDF file into editable excel file",
    icon: "src/assets/pdftoexcel.svg",
    link: "/pdf-to-excel",
    new: true,
  },
  {
    id: 6,
    title: "PDF to Powerpoint",
    description: "Transform PDF file into editable PPT file",
    icon: "src/assets/pdftopowerpoint.svg",
    link: "/pdf-to-powerpoint",
    new: true,
  },
  {
    id: 7,
    title: "Word to PDF",
    description: "Transform word document to PDF file",
    icon: "src/assets/wordtopdf.svg",
    link: "/word-to-pdf",
    new: true,
  },
  {
    id: 8,
    title: "Powerpoint to PDF",
    description: "Transform PDF file into image",
    icon: "src/assets/powerpointtopdf.svg",
    link: "/powerpoint-to-pdf",
    new: true,
  },
  {
    id: 9,
    title: "Excel to PDF",
    description: "Transform PDF file into image",
    icon: "src/assets/exceltopdf.svg",
    link: "/excel-to-pdf",
    new: true,
  },
  {
    id: 10,
    title: "More tools coming soon",
    description: "",
    icon: "", 
    link: "#",
    new: false,
  },
];
